# Generated by Django 6.0.2 on 2026-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0008_remove_article_tags_article_likes_alter_article_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
